package net.jwenzel.dashboard.match_history_card_fragment

import net.jwenzel.dashboard.dashboard.DashboardCardPresenterImpl

class MatchHistoryCardPresenterImpl(view: MatchHistoryCardView): DashboardCardPresenterImpl<MatchHistoryCardView>(view), MatchHistoryCardPresenter